from modules.module_Search import TestSearchSuite
from modules.module_Comment import TestCommentSuite
from modules.module_sendMassage import TestSendMassage
from modules.module_changePassword import TestChangePassword
from modules.module_ViewAReview import TestVisitareview
