# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSendMassage():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_messageFullComplete(self):
    self.driver.get("https://tinhte.vn/")
    self.driver.find_element(By.CSS_SELECTOR, ".jsx-203918857:nth-child(2) .jsx-2504361010 > .jsx-4205696072").click()
    self.driver.find_element(By.LINK_TEXT, "Xem tất cả").click()
    self.driver.find_element(By.CSS_SELECTOR, ".topCtrl span").click()
    self.driver.find_element(By.ID, "ctrl_recipients").click()
    self.driver.find_element(By.ID, "ctrl_recipients").send_keys("hoangthh1612, ")
    self.driver.find_element(By.ID, "ctrl_title").click()
    self.driver.find_element(By.ID, "ctrl_title").send_keys("Project_03")
    self.driver.switch_to.frame(0)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>fdafda fdafda l fdajfldaf</p>'}", element)
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".ctrlUnit:nth-child(3) .primary").click()
    self.driver.execute_script("window.scrollTo(0,100)")
    self.driver.close()
  
  def test_messageWithUnValidTitle(self):
    self.driver.get("https://tinhte.vn/")
    element = self.driver.find_element(By.CSS_SELECTOR, ".jsx-306557543 > .jsx-306557543")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".jsx-4205696072 > path:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "Xem tất cả").click()
    self.driver.find_element(By.CSS_SELECTOR, ".topCtrl span").click()
    self.driver.find_element(By.ID, "ctrl_recipients").click()
    self.driver.find_element(By.ID, "ctrl_recipients").send_keys("hoangthh1612, ")
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, "p").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>fdasfdaf dsfasfdas fdsafdas&nbsp;</p>'}", element)
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".ctrlUnit:nth-child(3) .primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".errorOverlay > .close").click()
    self.driver.close()
  
  def test_messageWithUnvalidPar(self):
    self.driver.get("https://tinhte.vn/")
    element = self.driver.find_element(By.CSS_SELECTOR, ".blue-switch")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".jsx-4205696072 > path:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Xem tất cả").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".topCtrl span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".topCtrl span").click()
    self.driver.find_element(By.ID, "ctrl_recipients").click()
    self.driver.find_element(By.ID, "ctrl_recipients").send_keys("fdafdsa")
    self.driver.find_element(By.ID, "ctrl_title").send_keys("Project_3")
    self.driver.switch_to.frame(0)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>fdasfda fdafdsa fdafda&nbsp;</p>'}", element)
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".ctrlUnit:nth-child(3) .primary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ctrlUnit:nth-child(3) .primary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "exposeMask").click()
    self.driver.close()
  
  def test_messageWithoutMess(self):
    self.driver.get("https://tinhte.vn/")
    self.driver.find_element(By.CSS_SELECTOR, ".jsx-4205696072 > path:nth-child(2)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".jsx-4205696072 > path:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Xem tất cả").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".topCtrl span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".topCtrl span").click()
    self.driver.find_element(By.ID, "ctrl_recipients").click()
    self.driver.find_element(By.ID, "ctrl_recipients").send_keys("hoangthh1612, ")
    self.driver.find_element(By.ID, "ctrl_title").send_keys("Project_03")
    self.driver.find_element(By.CSS_SELECTOR, ".ctrlUnit:nth-child(3) .primary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ctrlUnit:nth-child(3) .primary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".errorOverlay > .close").click()
    self.driver.close()
  
  def test_messageWithoutPar(self):
    self.driver.get("https://tinhte.vn/")
    self.driver.find_element(By.CSS_SELECTOR, ".jsx-4205696072 > path:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".jsx-4205696072 > path:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Xem tất cả").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".topCtrl span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".topCtrl span").click()
    self.driver.find_element(By.ID, "ctrl_title").click()
    self.driver.find_element(By.ID, "ctrl_title").send_keys("Project_3")
    self.driver.switch_to.frame(0)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>fdasf fdsafda fdafa fdafda&nbsp;</p>'}", element)
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".ctrlUnit:nth-child(3) .primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".errorOverlay > .close").click()
    self.driver.close()
  
